import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

import { ForgetPassProvider } from "@/context/ForgetPassContext";
import { DataProvider } from "@/context/DataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataProvider>

          <ForgetPassProvider>
        <Navbar/>

        {children}
        <ToastContainer/>
        </ForgetPassProvider>

        </DataProvider>
        </body>
    </html>
  );
}
