'use client'
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import { LoginProvider } from "../context/LoginContext";
import { ForgetPassProvider } from "@/context/ForgetPassContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LoginProvider>
          <ForgetPassProvider>
        <Navbar/>

        {children}
        <ToastContainer/>
        </ForgetPassProvider>
        </LoginProvider>
        </body>
    </html>
  );
}
